// The text to identify rules for each possible step that can be taken

module.exports = {
  NO_CHANGE : 'Oförändrad',
SIMPLIFY_ARITHMETIC : 'Förenkla',
DIVISION_BY_NEGATIVE_ONE : 'Dividera med -1',
DIVISION_BY_ONE : 'Dividera med 1',
MULTIPLY_BY_ZERO : 'Multiplicera med 0',
REARRANGE_COEFF : 'Ordna om koefficienter',
REDUCE_EXPONENT_BY_ZERO : 'Ta bort exponent med 0',
REDUCE_ZERO_NUMERATOR : 'Ta bort täljare med 0',
REMOVE_ADDING_ZERO : 'Ta bort 0',
REMOVE_EXPONENT_BY_ONE : 'Ta bort exponenten 1',
REMOVE_EXPONENT_BASE_ONE : 'Ta bort exponent när bas är 1',
REMOVE_MULTIPLYING_BY_NEGATIVE_ONE : 'Ta bort multiplikation med -1',
REMOVE_MULTIPLYING_BY_ONE : 'Ta bort multiplikation med 1',
RESOLVE_DOUBLE_MINUS : 'Dubbla minus blir plus',
COLLECT_AND_COMBINE_LIKE_TERMS : 'Samla och kombinera termer av samma sort',
COLLECT_LIKE_TERMS : 'Samla termer av samma sort',
COLLECT_CONSTANT_EXPONENTS : 'Samla konstanta exponenter',
ADD_COEFFICIENT_OF_ONE : 'Lägg till koefficienter som inte är utskrivna',
ADD_POLYNOMIAL_TERMS : 'Addera alla termer av samma sort',
GROUP_COEFFICIENTS : 'Gruppera koefficienter',
UNARY_MINUS_TO_NEGATIVE_ONE : 'Skriv om minus tecken till (-1)',
ADD_EXPONENT_OF_ONE : 'Lägg till exponent av 1',
COLLECT_POLYNOMIAL_EXPONENTS : 'Samla polynoma exponenter',
MULTIPLY_COEFFICIENTS : 'Multiplicera koefficienter ',
MULTIPLY_POLYNOMIAL_TERMS : 'Multiplicera polynom',
BREAK_UP_FRACTION : 'Dela upp bråk',
CANCEL_MINUSES : 'Kancellera minustecken',
CANCEL_TERMS : 'Kancellera termer',
SIMPLIFY_FRACTION : 'Förenkla bråk',
SIMPLIFY_SIGNS : 'Förnekla',
FIND_GCD : 'Sök största gemensamma faktor',
CANCEL_GCD : 'Kancellera största gemensamma faktor',
CONVERT_MIXED_NUMBER_TO_IMPROPER_FRACTION : 'Skriv om från blandad form till bråk',
IMPROPER_FRACTION_NUMERATOR : 'Felaktig täljare',
ADD_FRACTIONS : 'Addera bråk',
ADD_NUMERATORS : 'Addera täljare',
COMBINE_NUMERATORS : 'Kombinera täljare',
COMMON_DENOMINATOR : 'Gemensam nämnare',
CONVERT_INTEGER_TO_FRACTION : 'Skriv om heltal till bråk',
DIVIDE_FRACTION_FOR_ADDITION : 'Dividera bråk för addition',
MULTIPLY_DENOMINATORS : 'Multiplicera nämnare',
MULTIPLY_NUMERATORS : 'Multiplicera täljare',
MULTIPLY_FRACTIONS : 'Multiplicera bråk',
SIMPLIFY_DIVISION : 'Förenkla division',
MULTIPLY_BY_INVERSE : 'Multiplicera med inversen',
DISTRIBUTE : 'Multiplicera in',
DISTRIBUTE_NEGATIVE_ONE : 'Multiplicera med -1',
SIMPLIFY_TERMS : 'Förenkla termer',
EXPAND_EXPONENT : 'Utveckla exponenten',
ABSOLUTE_VALUE : 'Absolut beloppet',
CANCEL_EXPONENT : 'Kancellera exponenten',
CANCEL_EXPONENT_AND_ROOT : 'Kancellera exponenten och roten',
CANCEL_ROOT : 'Kancellera roten',
COMBINE_UNDER_ROOT : 'COMBINE_UNDER_ROOT',
CONVERT_MULTIPLICATION_TO_EXPONENT : 'CONVERT_MULTIPLICATION_TO_EXPONENT',
DISTRIBUTE_NTH_ROOT : 'DISTRIBUTE_NTH_ROOT',
EVALUATE_DISTRIBUTED_NTH_ROOT : 'EVALUATE_DISTRIBUTED_NTH_ROOT',
FACTOR_INTO_PRIMES : 'Faktorisera till primtal',
GROUP_TERMS_BY_ROOT : 'Lägg ihop termer beroende på rötter',
NTH_ROOT_VALUE : 'n:te rotens värde',
ADD_NTH_ROOTS : 'lägg till n:te roten',
MULTIPLY_NTH_ROOTS : 'multiplicera n:te roten',
ADD_TO_BOTH_SIDES : 'Addera på båda led',
DIVIDE_FROM_BOTH_SIDES : 'Dividera från båda led',
MULTIPLY_BOTH_SIDES_BY_INVERSE_FRACTION : 'Multiplicera båda sidor med inversen',
MULTIPLY_BOTH_SIDES_BY_NEGATIVE_ONE : 'Multiplicera båda sidor med -1',
MULTIPLY_TO_BOTH_SIDES : 'Multiplicera båda sidor',
SIMPLIFY_LEFT_SIDE : 'Förenkla vänster led',
SIMPLIFY_RIGHT_SIDE : 'Förenkla höger led',
SUBTRACT_FROM_BOTH_SIDES : 'Subtrahera från båda sidor',
SWAP_SIDES : 'Byt sida',
FIND_ROOTS : 'Sök rötter',
STATEMENT_IS_TRUE : 'Påståendet är sant',
STATEMENT_IS_FALSE : 'Påståendet är falskt',
FACTOR_SYMBOL : 'FACTOR_SYMBOL',
FACTOR_DIFFERENCE_OF_SQUARES : 'FACTOR_DIFFERENCE_OF_SQUARES',
FACTOR_PERFECT_SQUARE : 'FACTOR_PERFECT_SQUARE',
FACTOR_SUM_PRODUCT_RULE : 'FACTOR_SUM_PRODUCT_RULE',
BREAK_UP_TERM : 'Dela upp term',
};
